std = "lua51"

globals = {}
read_globals = {
  "CreateFrame",
  "C_Timer",
  "C_ChatInfo",
  "C_Texture",
  "IsInGroup",
  "IsInRaid",
  "GetNumGroupMembers",
  "GetNumSubgroupMembers",
  "GetRaidRosterInfo",
  "UnitClass",
  "UnitFullName",
  "UnitIsUnit",
  "strsplit",
  "strtrim",
  "UnitName",
  "UnitExists",
  "GetRealmName",
  "GetSpecialization",
  "GetSpecializationInfo",
  "GetInspectSpecialization",
  "GetSpecializationInfoByID",
  "CanInspect",
  "time",
  "date",
  "GetServerTime",
  "C_DateAndTime",
  "GameTooltip",
  "GameTooltip_Hide",
  "Settings",
  "UIParent",
  "UIPanelCloseButton",
  "RAID_CLASS_COLORS",
}