local _, SF = ...

SF.MouseTracer = SF.MouseTracer or {}

local MIN_SPACING = 6
local MAX_TRAIL_LENGTH = 400

SF.MouseTracer.Constants = {
	MIN_SPACING = MIN_SPACING,
	MAX_TRAIL_LENGTH = MAX_TRAIL_LENGTH,
	MIN_TRAIL_LENGTH = 80,
	MIN_FADE_DURATION = 0.2,
	MAX_FADE_DURATION = 1.5,
	MIN_THICKNESS = 6,
	MAX_THICKNESS = 28,
	MIN_RAINBOW_SPEED = 0.25,
	MAX_RAINBOW_SPEED = 3.0,
	MIN_OPACITY = 0.2,
	MAX_OPACITY = 1.0,

	DEFAULT_TRAIL_LENGTH = 200,
	DEFAULT_FADE_DURATION = 0.50,
	DEFAULT_THICKNESS = 14,
	DEFAULT_RAINBOW_SPEED = 1.0,
	DEFAULT_OPACITY = 0.70,

	MAX_POINTS = math.ceil(MAX_TRAIL_LENGTH / MIN_SPACING) + 2,
	MAX_SEGMENTS = math.ceil(MAX_TRAIL_LENGTH / MIN_SPACING) + 1,
	MAX_NEW_POINTS_PER_TICK = 12,
	TELEPORT_DISTANCE = 250,

	ACTIVE_SAMPLE_INTERVAL = 1 / 60,
	FADE_INTERVAL = 1 / 30,
	IDLE_POLL_INTERVAL = 1 / 60,
	SNAPSHOT_DEBOUNCE = 0.35,
	SNAPSHOT_TICKER_INTERVAL = 0.1,
	ALPHA_EPSILON = 0.01,

	HUE_PER_PIXEL = 1 / 200,

	SETTING_KEYS = {
		"enabled",
		"trailLength",
		"fadeDuration",
		"thickness",
		"rainbowSpeed",
		"opacity",
	},
}
